// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD03zr-nwd3bb7ONuZiQ9jZtOqfzLfrog',
    appId: '1:655739936184:web:568966006763f217d7434d',
    messagingSenderId: '655739936184',
    projectId: 'everest-spelling-bee-26',
    authDomain: 'everest-spelling-bee-26.firebaseapp.com',
    storageBucket: 'everest-spelling-bee-26.firebasestorage.app',
    measurementId: 'G-N95WTL70SK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3PLKkQLPYOyEWRXRCx74kt1Z5GheWIlg',
    appId: '1:655739936184:android:eb4a6aeed8530238d7434d',
    messagingSenderId: '655739936184',
    projectId: 'everest-spelling-bee-26',
    storageBucket: 'everest-spelling-bee-26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpZy7X0n2RgJ9YMFJsLP2BWEFM1a37k7Q',
    appId: '1:655739936184:ios:708898dfba444ef8d7434d',
    messagingSenderId: '655739936184',
    projectId: 'everest-spelling-bee-26',
    storageBucket: 'everest-spelling-bee-26.firebasestorage.app',
    iosBundleId: 'com.example.spellingBee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpZy7X0n2RgJ9YMFJsLP2BWEFM1a37k7Q',
    appId: '1:655739936184:ios:708898dfba444ef8d7434d',
    messagingSenderId: '655739936184',
    projectId: 'everest-spelling-bee-26',
    storageBucket: 'everest-spelling-bee-26.firebasestorage.app',
    iosBundleId: 'com.example.spellingBee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAD03zr-nwd3bb7ONuZiQ9jZtOqfzLfrog',
    appId: '1:655739936184:web:7987c19f766734afd7434d',
    messagingSenderId: '655739936184',
    projectId: 'everest-spelling-bee-26',
    authDomain: 'everest-spelling-bee-26.firebaseapp.com',
    storageBucket: 'everest-spelling-bee-26.firebasestorage.app',
    measurementId: 'G-9HV31RPT66',
  );
}
